# _*_ coding: utf-8 _*_

class FrsConstant(object):
    endPoint = "https://face.cn-north-1.myhuaweicloud.com"
    region = "cn-north-1"
    faceDetectUri = "/v1/%s/face-detect"
    faceCompareUri = "/v1/%s/face-compare"
    faceSearchUri = "/v1/%s/face-sets/%s/search"
    faceAddUri = "/v1/%s/face-sets/%s/faces"
    faceGetRangeUri = "/v1/%s/face-sets/%s/faces?offset=%d&limit=%d"
    faceGetOneUri = "/v1/%s/face-sets/%s/faces?face_id=%s"
    faceGetBaseUri = "/v1/%s/face-sets/%s/faces"
    faceDeleteByExternalImageIdUri = "/v1/%s/face-sets/%s/faces?external_image_id=%s"
    faceDeleteByFaceIdUri = "/v1/%s/face-sets/%s/faces?face_id=%s"
    faceDeleteByFieldIdUri = "/v1/%s/face-sets/%s/faces?%s=%s"
    faceSetCreateUri = "/v1/%s/face-sets"
    faceSetGetAllUri = "/v1/%s/face-sets"
    faceSetGetOneUri = "/v1/%s/face-sets/%s"
    faceSetDeleteUri = "/v1/%s/face-sets/%s"
    liveDetectUri = "/v1/%s/live-detect"
    faceQualityUri = "/v1/%s/face/quality/face-quality"
    blurClassifyUri = "/v1/%s/face/quality/blur-classify"
    headPoseEstimate = "/v1/%s/face/quality/head-pose-estimate"